//
// Created by kt on 09/04/24.
//

#ifndef CLION_LEETCODE_WORKSPACE1_UPDATETOCPLUS20TEST_H
#define CLION_LEETCODE_WORKSPACE1_UPDATETOCPLUS20TEST_H


class updatetocplus20test {

};


#endif //CLION_LEETCODE_WORKSPACE1_UPDATETOCPLUS20TEST_H
